{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otelcollector.fullname" . }}
  labels:
    {{- include "otelcollector.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end }}
{{- end }}
